# Generated by Django 5.1.2 on 2024-10-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='favorite_movie',
            field=models.JSONField(blank=True, default=list, verbose_name='Favorite movie'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='favorite_video',
            field=models.JSONField(blank=True, default=list, verbose_name='Favorite video'),
        ),
    ]
