# Generated by Django 5.1.2 on 2024-10-28 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0002_botuser_favorite_movie_botuser_favorite_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='favorite_movie',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='favorite_video',
        ),
    ]
